compile: # see help(tensorflow.keras.Model.compile) for options
    optimizer: 
        class_path: tensorflow.keras.optimizers.Adam
        init_args:
            learning_rate: 0.001
    loss: 
        class_path: tensorflow.keras.losses.SparseCategoricalCrossentropy
        init_args:
            from_logits: true
    metrics:
        - class_path: tensorflow.keras.metrics.SparseCategoricalAccuracy
    run_eagerly: false
fit: # See help(tensorflow.keras.Model.fit) for options. Only supports tf.Dataset inputs
    verbose: 2
    epochs: 20
    callbacks:
        - class_path: tensorflow.keras.callbacks.TensorBoard
          init_args:
              log_dir: fashionmnist_conv/tensorboard
              profile_batch: '0,20'
        - class_path: tensorflow.keras.callbacks.ProgbarLogger
        - class_path: tensorflow.keras.callbacks.ModelCheckpoint
          init_args:
             filepath: fashionmnist_conv
    validation_freq: 1
dataset: # see help(tensorflow_datasets.load)
    name: fashion_mnist
    batch_size: 512
    split: ['train[0%:80%]', 'train[80%:100%]']
x_cast: float32
y_cast: null 
model_wrapper:
    model:
        class_path: tf_hpc.nn.models.ConvolutionClassifier
        init_args:
            tag: convolution_classifier
            out_dim: 10
            activation: relu
            hidden_layers: [1024,512,256]
            conv_channels: [64,64]
            conv_kernels: [2,2]
            pooling_kernels: [2,2]
strategy: null
